[tools]
powershell = "7"
python = "3.10"
uv = "latest"

[env]
UV_LINK_MODE="copy"
_.path = [".venv", ".venv/Scripts", ".venv/bin"]

[tasks.init]
run = "uv venv --python 3.10.16 --seed"

[tasks.clean]
run = "pwsh -NoProfile -File scripts/Invoke-Clean-Arcfaces-Build.ps1"

[tasks.build]
run = "pwsh -NoProfile -File scripts/Invoke-Build-Run-Arcfaces.ps1"

[tasks.build-wheels]
run = "pwsh -NoProfile -File scripts/Invoke-Build-Arcfaces-Wheels.ps1"

[tasks.bump]
run = "pwsh -NoProfile -File scripts/Invoke-Bump-Arcfaces-Version.ps1 -BumpVersion auto"
